service: aws-ses-serverless-example

provider:
  name: aws
  runtime: nodejs14.x
  stage: development
  region: us-east-1

plugins:
  - serverless-webpack

functions:
  sendMail:
    handler: handler.sendMail
    description: Send email using SES service.
    memorySize: 1024
    timeout: 5
    events:
      - http:
          path: sendMail
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
